### ISSUE TITLE
repository name does not follow convention specified 

### ISSUE THREAD

**Issue by shabbirabdul** [SoftwareEngineeringToolDemos/FSE-2014-XMLMate#2]
repository name should follow our convention (conf-year-toolname)

**Comment by CaptainEmerson** [comment]
the title was fine, but you're not using labels

**Comment by shabbirabdul** [comment]
Hi Professor,

I have changed it.

Thanks, 

Shabbir

—

**Comment by CaptainEmerson** [comment]
the original title was fine, but you're still not using labels

**Comment by shabbirabdul** [comment]
@CaptainEmerson 
I am not sure if this should be right title.
Should it be repository name does not follow convention specified [FSE-2014-XMLMate] ?

**Comment by CaptainEmerson** [comment]
You're still not using labels. https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/

**Comment by shabbirabdul** [comment]
@CaptainEmerson I can only create new labels for projects under my repositories. Do I have to fork the repository I am reviewing before I create issues?
I  do not see a create label option when I am trying to create issues.

Thanks,
Shabbir

**Comment by CaptainEmerson** [comment]
That makes sense. I think you'll need to ask for admin permission from the current owner. I'll have to update the assignment instructions -- unless you have a better idea?

**Comment by shabbirabdul** [comment]
@CaptainEmerson 
Can we ask the owners of the repositories to create all possible labels themselves?

**Comment by CaptainEmerson** [comment]
Seems like that will be more work than the reviewers doing it. If we could make labels on an organization-wide basis, that would be easier, but I don't think that is possible.

**Comment by mhhassan** [comment]
@CaptainEmerson 
Professor, I have created a team (Craven) on our organization with me and my teammates and have asked the team which we will review to give our team Write access on their repos (as a Team) to create labels (for issues).

I have also asked them to create a team as well so that we can do the same on our tools. I hope that's ok?

**Comment by CaptainEmerson** [comment]
Sounds ok, thought I'm unsure if write access gives you permission to add labels.

**Comment by mhhassan** [comment]
@CaptainEmerson 
Write access seemed to allow creation of new labels. I think we should be good now.

**Comment by CaptainEmerson** [comment]
:+1:

**Comment by shabbirabdul** [comment]
tool name modified as per the specification
